// Shared error code definitions for Vibecodr
// Centralized so Workers, Next.js, and runtimes can agree on E-VIBECODR-#### semantics.

export type ErrorCategory =
  | "auth"
  | "moderation"
  | "api"
  | "import"
  | "capsule"
  | "manifest"
  | "runtime"
  | "og-image"
  | "proxy"
  | "internal";

export type ErrorSeverity = "info" | "warning" | "error";

export interface ErrorDefinition {
  code: string;
  category: ErrorCategory;
  httpStatus: number;
  severity: ErrorSeverity;
  userMessage: string;
  logMessage: string;
}

const definitions: Record<string, ErrorDefinition> = {
  // 0xxx: core platform and auth
  "E-VIBECODR-0001": {
    code: "E-VIBECODR-0001",
    category: "auth",
    httpStatus: 401,
    severity: "error",
    userMessage: "Authentication failed. Please sign in again.",
    logMessage: "Auth verification failed",
  },
  "E-VIBECODR-0002": {
    code: "E-VIBECODR-0002",
    category: "moderation",
    httpStatus: 403,
    severity: "error",
    userMessage: "You do not have permission to perform this action.",
    logMessage: "Moderation access denied",
  },
  "E-VIBECODR-0003": {
    code: "E-VIBECODR-0003",
    category: "auth",
    httpStatus: 500,
    severity: "error",
    userMessage: "Unable to attach session. Please refresh and try again.",
    logMessage: "Clerk token injection failed in edge proxy",
  },
  "E-VIBECODR-0004": {
    code: "E-VIBECODR-0004",
    category: "auth",
    httpStatus: 401,
    severity: "error",
    userMessage: "Authentication failed. Please sign in again.",
    logMessage: "Worker token is missing required claims",
  },
  "E-VIBECODR-0005": {
    code: "E-VIBECODR-0005",
    category: "auth",
    httpStatus: 401,
    severity: "error",
    userMessage: "Authentication failed. Please sign in again.",
    logMessage: "Worker token audience/azp mismatch",
  },
  "E-VIBECODR-0006": {
    code: "E-VIBECODR-0006",
    category: "auth",
    httpStatus: 401,
    severity: "error",
    userMessage: "Authentication failed. Please sign in again.",
    logMessage: "Worker token signature verification failed",
  },
  "E-VIBECODR-0007": {
    code: "E-VIBECODR-0007",
    category: "auth",
    httpStatus: 502,
    severity: "error",
    userMessage: "Authentication service is temporarily unavailable. Please retry.",
    logMessage: "Clerk JWKS download failed",
  },
  "E-VIBECODR-0008": {
    code: "E-VIBECODR-0008",
    category: "auth",
    httpStatus: 502,
    severity: "error",
    userMessage: "Authentication service is temporarily unavailable. Please retry.",
    logMessage: "Clerk JWKS response malformed",
  },
  "E-VIBECODR-0009": {
    code: "E-VIBECODR-0009",
    category: "auth",
    httpStatus: 500,
    severity: "error",
    userMessage: "Authentication configuration is invalid. Please contact support.",
    logMessage: "Auth audience env JSON parse failed",
  },

  // 01xx: social and moderation helpers
  "E-VIBECODR-0101": {
    code: "E-VIBECODR-0101",
    category: "api",
    httpStatus: 201,
    severity: "warning",
    userMessage: "Post created, but counters may be temporarily stale.",
    logMessage: "createPost counter update failed",
  },
  "E-VIBECODR-0102": {
    code: "E-VIBECODR-0102",
    category: "moderation",
    httpStatus: 503,
    severity: "error",
    userMessage: "Quarantine is temporarily unavailable. Please contact an administrator.",
    logMessage: "Moderation quarantine action failed while resolving report",
  },
  "E-VIBECODR-0103": {
    code: "E-VIBECODR-0103",
    category: "moderation",
    httpStatus: 503,
    severity: "error",
    userMessage: "Quarantine is temporarily unavailable. Please contact an administrator.",
    logMessage: "Direct post quarantine failed",
  },
  "E-VIBECODR-0104": {
    code: "E-VIBECODR-0104",
    category: "moderation",
    httpStatus: 503,
    severity: "error",
    userMessage: "Quarantine is temporarily unavailable. Please contact an administrator.",
    logMessage: "Direct comment quarantine failed",
  },
  "E-VIBECODR-0105": {
    code: "E-VIBECODR-0105",
    category: "moderation",
    httpStatus: 503,
    severity: "error",
    userMessage: "Quarantine is temporarily unavailable. Please contact an administrator.",
    logMessage: "Direct post unquarantine failed",
  },
  "E-VIBECODR-0106": {
    code: "E-VIBECODR-0106",
    category: "moderation",
    httpStatus: 503,
    severity: "error",
    userMessage: "Quarantine is temporarily unavailable. Please contact an administrator.",
    logMessage: "Direct comment unquarantine failed",
  },
  "E-VIBECODR-0107": {
    code: "E-VIBECODR-0107",
    category: "moderation",
    httpStatus: 500,
    severity: "error",
    userMessage: "We could not process that moderation action. Please retry.",
    logMessage: "Moderation action error body JSON parse failed",
  },
  "E-VIBECODR-0108": {
    code: "E-VIBECODR-0108",
    category: "api",
    httpStatus: 202,
    severity: "warning",
    userMessage: "We saved your action, but profile counts may be temporarily stale.",
    logMessage: "User counters update failed",
  },
  "E-VIBECODR-0109": {
    code: "E-VIBECODR-0109",
    category: "api",
    httpStatus: 202,
    severity: "warning",
    userMessage: "We saved your action, but post stats may be temporarily stale.",
    logMessage: "Post stats update failed",
  },
  "E-VIBECODR-0110": {
    code: "E-VIBECODR-0110",
    category: "capsule",
    httpStatus: 202,
    severity: "warning",
    userMessage: "Remix counts may be temporarily delayed.",
    logMessage: "Remix counter update failed during publish",
  },
  "E-VIBECODR-0111": {
    code: "E-VIBECODR-0111",
    category: "capsule",
    httpStatus: 202,
    severity: "warning",
    userMessage: "We published your remix, but linking to the parent may be delayed.",
    logMessage: "Remix relationship insert failed during publish",
  },

  // 02xx: capsule manifest parsing and validation in feed/player paths
  "E-VIBECODR-0201": {
    code: "E-VIBECODR-0201",
    category: "manifest",
    httpStatus: 500,
    severity: "error",
    userMessage: "This app is currently unavailable.",
    logMessage: "Capsule manifest JSON parse failed",
  },
  "E-VIBECODR-0202": {
    code: "E-VIBECODR-0202",
    category: "manifest",
    httpStatus: 500,
    severity: "error",
    userMessage: "This app is currently unavailable.",
    logMessage: "Capsule manifest validation failed",
  },
  "E-VIBECODR-0203": {
    code: "E-VIBECODR-0203",
    category: "manifest",
    httpStatus: 500,
    severity: "error",
    userMessage: "This app is currently unavailable.",
    logMessage: "Required capsule manifest missing for source view",
  },
  "E-VIBECODR-0204": {
    code: "E-VIBECODR-0204",
    category: "manifest",
    httpStatus: 500,
    severity: "error",
    userMessage: "Preview handoff failed. Please retry.",
    logMessage: "Preview handoff write failed",
  },
  "E-VIBECODR-0205": {
    code: "E-VIBECODR-0205",
    category: "manifest",
    httpStatus: 500,
    severity: "error",
    userMessage: "Preview handoff failed. Please retry.",
    logMessage: "Preview handoff read failed",
  },
  "E-VIBECODR-0206": {
    code: "E-VIBECODR-0206",
    category: "manifest",
    httpStatus: 502,
    severity: "error",
    userMessage: "We could not load this app's configuration. Please retry.",
    logMessage: "Capsule manifest preload or analytics write failed",
  },

  // 03xx: proxy and rate limit
  "E-VIBECODR-0300": {
    code: "E-VIBECODR-0300",
    category: "proxy",
    httpStatus: 403,
    severity: "error",
    userMessage: "Network proxy is disabled for this workspace.",
    logMessage: "Network proxy is disabled",
  },
  "E-VIBECODR-0301": {
    code: "E-VIBECODR-0301",
    category: "proxy",
    httpStatus: 400,
    severity: "error",
    userMessage: "Proxy allowlist is misconfigured. Please update the allowed hosts.",
    logMessage: "Proxy allowlist parse failed",
  },
  "E-VIBECODR-0302": {
    code: "E-VIBECODR-0302",
    category: "proxy",
    httpStatus: 403,
    severity: "error",
    userMessage: "That host is blocked for security reasons.",
    logMessage: "Proxy target host is blocked",
  },
  "E-VIBECODR-0303": {
    code: "E-VIBECODR-0303",
    category: "proxy",
    httpStatus: 500,
    severity: "error",
    userMessage: "Proxy rate limit storage is unavailable right now.",
    logMessage: "Proxy rate limit storage failed",
  },
  "E-VIBECODR-0304": {
    code: "E-VIBECODR-0304",
    category: "proxy",
    httpStatus: 500,
    severity: "error",
    userMessage: "Proxy rate limit storage is misconfigured. Please retry later.",
    logMessage: "Proxy rate limit storage misconfiguration detected",
  },
  "E-VIBECODR-0305": {
    code: "E-VIBECODR-0305",
    category: "proxy",
    httpStatus: 403,
    severity: "error",
    userMessage: "Network proxy is not available on this plan.",
    logMessage: "Proxy request rejected for current plan",
  },
  "E-VIBECODR-0306": {
    code: "E-VIBECODR-0306",
    category: "proxy",
    httpStatus: 403,
    severity: "error",
    userMessage: "This app is not allowed to call that host.",
    logMessage: "Proxy host list is empty or disallows the target",
  },
  "E-VIBECODR-0307": {
    code: "E-VIBECODR-0307",
    category: "proxy",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Proxy rate limiting is degraded. Requests may be limited conservatively.",
    logMessage: "Proxy rate limit table init failed",
  },
  "E-VIBECODR-0308": {
    code: "E-VIBECODR-0308",
    category: "proxy",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Proxy rate limit check failed. Please retry.",
    logMessage: "Proxy D1 rate limit check failed",
  },
  "E-VIBECODR-0310": {
    code: "E-VIBECODR-0310",
    category: "proxy",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Rate limit service is unavailable. Please retry shortly.",
    logMessage: "Public rate limit check failed",
  },
  "E-VIBECODR-0311": {
    code: "E-VIBECODR-0311",
    category: "proxy",
    httpStatus: 429,
    severity: "error",
    userMessage: "You have hit the capsule rate limit. Please slow down and retry.",
    logMessage: "Capsule API rate limit exceeded",
  },
  "E-VIBECODR-0312": {
    code: "E-VIBECODR-0312",
    category: "proxy",
    httpStatus: 429,
    severity: "error",
    userMessage: "You have hit the artifact rate limit. Please retry later.",
    logMessage: "Artifact request rate limit exceeded",
  },
  "E-VIBECODR-0313": {
    code: "E-VIBECODR-0313",
    category: "proxy",
    httpStatus: 429,
    severity: "error",
    userMessage: "You have hit the oEmbed rate limit. Please retry later.",
    logMessage: "oEmbed rate limit exceeded",
  },
  "E-VIBECODR-0314": {
    code: "E-VIBECODR-0314",
    category: "proxy",
    httpStatus: 429,
    severity: "error",
    userMessage: "You have hit the og-image rate limit. Please retry later.",
    logMessage: "og-image rate limit exceeded",
  },
  "E-VIBECODR-0315": {
    code: "E-VIBECODR-0315",
    category: "proxy",
    httpStatus: 429,
    severity: "error",
    userMessage: "You have hit the embed rate limit. Please retry later.",
    logMessage: "Embed rate limit exceeded",
  },

  // 04xx: pagination, storage, sync, cleanup
  "E-VIBECODR-0400": {
    code: "E-VIBECODR-0400",
    category: "api",
    httpStatus: 400,
    severity: "error",
    userMessage: "Invalid comment data.",
    logMessage: "Comment validation failed",
  },
  "E-VIBECODR-0401": {
    code: "E-VIBECODR-0401",
    category: "api",
    httpStatus: 400,
    severity: "error",
    userMessage: "Invalid pagination: limit must be an integer.",
    logMessage: "Pagination limit was not an integer",
  },
  "E-VIBECODR-0402": {
    code: "E-VIBECODR-0402",
    category: "api",
    httpStatus: 400,
    severity: "error",
    userMessage: "Invalid pagination: limit must be at least 1.",
    logMessage: "Pagination limit below minimum",
  },
  "E-VIBECODR-0403": {
    code: "E-VIBECODR-0403",
    category: "api",
    httpStatus: 400,
    severity: "error",
    userMessage: "Invalid pagination: offset must be an integer.",
    logMessage: "Pagination offset was not an integer",
  },
  "E-VIBECODR-0404": {
    code: "E-VIBECODR-0404",
    category: "api",
    httpStatus: 400,
    severity: "error",
    userMessage: "Invalid pagination: offset cannot be negative.",
    logMessage: "Pagination offset was negative",
  },
  "E-VIBECODR-0405": {
    code: "E-VIBECODR-0405",
    category: "capsule",
    httpStatus: 400,
    severity: "error",
    userMessage: "Storage quota exceeded for this operation.",
    logMessage: "Storage quota exceeded during accounting",
  },
  "E-VIBECODR-0406": {
    code: "E-VIBECODR-0406",
    category: "capsule",
    httpStatus: 500,
    severity: "error",
    userMessage: "Failed to record storage usage. Please retry.",
    logMessage: "Failed to record storage usage",
  },
  "E-VIBECODR-0407": {
    code: "E-VIBECODR-0407",
    category: "capsule",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Cleanup of draft assets failed. Retrying may be required.",
    logMessage: "Cleanup draft assets failed",
  },
  "E-VIBECODR-0408": {
    code: "E-VIBECODR-0408",
    category: "capsule",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Cleanup of this draft app failed. Retrying may be required.",
    logMessage: "Cleanup draft capsule failed",
  },
  "E-VIBECODR-0409": {
    code: "E-VIBECODR-0409",
    category: "capsule",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Cleanup of draft bundle failed. Retrying may be required.",
    logMessage: "Cleanup draft R2 bundle failed",
  },
  "E-VIBECODR-0410": {
    code: "E-VIBECODR-0410",
    category: "capsule",
    httpStatus: 500,
    severity: "error",
    userMessage: "Failed to initialize user storage. Please retry.",
    logMessage: "Bootstrap user storage failed",
  },
  "E-VIBECODR-0411": {
    code: "E-VIBECODR-0411",
    category: "capsule",
    httpStatus: 500,
    severity: "error",
    userMessage: "Failed to allocate a fallback handle for this user.",
    logMessage: "User handle allocation failed during bootstrap",
  },

  // 06xx: capsule access control
  "E-VIBECODR-0601": {
    code: "E-VIBECODR-0601",
    category: "capsule",
    httpStatus: 404,
    severity: "error",
    userMessage: "This app is not available.",
    logMessage: "Capsule access blocked by policy or visibility",
  },
  "E-VIBECODR-0602": {
    code: "E-VIBECODR-0602",
    category: "capsule",
    httpStatus: 503,
    severity: "warning",
    userMessage: "WebGL is not available on this device; the background was disabled.",
    logMessage: "Capsule experience requires WebGL but it was unavailable",
  },
  "E-VIBECODR-0603": {
    code: "E-VIBECODR-0603",
    category: "capsule",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Run analytics are temporarily degraded.",
    logMessage: "Run quota analytics write failed",
  },
  "E-VIBECODR-0604": {
    code: "E-VIBECODR-0604",
    category: "capsule",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Run quota snapshot failed. Limits may be conservative.",
    logMessage: "Run quota snapshot failed",
  },
  "E-VIBECODR-0605": {
    code: "E-VIBECODR-0605",
    category: "capsule",
    httpStatus: 429,
    severity: "error",
    userMessage: "Play limit exceeded for this app.",
    logMessage: "Run quota exceeded",
  },
  "E-VIBECODR-0606": {
    code: "E-VIBECODR-0606",
    category: "capsule",
    httpStatus: 500,
    severity: "error",
    userMessage: "Failed to complete run updates. Please retry.",
    logMessage: "completeRun update failed",
  },
  "E-VIBECODR-0607": {
    code: "E-VIBECODR-0607",
    category: "capsule",
    httpStatus: 429,
    severity: "error",
    userMessage: "Play limit exceeded for this app.",
    logMessage: "Run quota exceeded while completing run",
  },
  "E-VIBECODR-0608": {
    code: "E-VIBECODR-0608",
    category: "capsule",
    httpStatus: 400,
    severity: "error",
    userMessage: "Run request was invalid.",
    logMessage: "Run request validation failed",
  },
  "E-VIBECODR-0609": {
    code: "E-VIBECODR-0609",
    category: "capsule",
    httpStatus: 500,
    severity: "error",
    userMessage: "Run analytics write failed. Please retry.",
    logMessage: "Run analytics write failed",
  },
  "E-VIBECODR-0610": {
    code: "E-VIBECODR-0610",
    category: "capsule",
    httpStatus: 400,
    severity: "error",
    userMessage: "URL must use http or https.",
    logMessage: "Embed request used an invalid protocol",
  },
  "E-VIBECODR-0611": {
    code: "E-VIBECODR-0611",
    category: "capsule",
    httpStatus: 400,
    severity: "error",
    userMessage: "URL target is invalid for embedding.",
    logMessage: "Embed target path invalid",
  },
  "E-VIBECODR-0612": {
    code: "E-VIBECODR-0612",
    category: "capsule",
    httpStatus: 404,
    severity: "error",
    userMessage: "Content is not embeddable or was not found.",
    logMessage: "Embed target not embeddable",
  },
  "E-VIBECODR-0613": {
    code: "E-VIBECODR-0613",
    category: "capsule",
    httpStatus: 502,
    severity: "error",
    userMessage: "Embedding failed. Please retry.",
    logMessage: "oEmbed generation failed",
  },
  "E-VIBECODR-0614": {
    code: "E-VIBECODR-0614",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Run update failed. Please retry.",
    logMessage: "markRunFailed update failed",
  },
  "E-VIBECODR-0615": {
    code: "E-VIBECODR-0615",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Run telemetry probe failed. Please retry.",
    logMessage: "Run schema probe failed",
  },
  "E-VIBECODR-0616": {
    code: "E-VIBECODR-0616",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Run telemetry schema is missing fields.",
    logMessage: "Run schema missing error column",
  },

  // 05xx: feed, share, reporting, runtime client UX
  "E-VIBECODR-0501": {
    code: "E-VIBECODR-0501",
    category: "api",
    httpStatus: 500,
    severity: "error",
    userMessage: "We could not load this content. Please retry.",
    logMessage: "Runtime artifact bundle or feed fetch failed",
  },
  "E-VIBECODR-0502": {
    code: "E-VIBECODR-0502",
    category: "api",
    httpStatus: 400,
    severity: "warning",
    userMessage: "Sharing failed or was cancelled. Please retry.",
    logMessage: "Share action failed",
  },
  "E-VIBECODR-0503": {
    code: "E-VIBECODR-0503",
    category: "api",
    httpStatus: 400,
    severity: "warning",
    userMessage: "Copy to clipboard failed. Please retry.",
    logMessage: "Clipboard write failed",
  },
  "E-VIBECODR-0504": {
    code: "E-VIBECODR-0504",
    category: "api",
    httpStatus: 500,
    severity: "error",
    userMessage: "We could not process this request. Please retry.",
    logMessage: "Request body parse or manifest write failed",
  },
  "E-VIBECODR-0505": {
    code: "E-VIBECODR-0505",
    category: "api",
    httpStatus: 500,
    severity: "error",
    userMessage: "We could not complete this request. Please retry.",
    logMessage: "Delete or fetch failed for requested resource",
  },
  "E-VIBECODR-0506": {
    code: "E-VIBECODR-0506",
    category: "moderation",
    httpStatus: 500,
    severity: "error",
    userMessage: "Report submission failed. Please retry.",
    logMessage: "Report submit error body parse failed",
  },
  "E-VIBECODR-0507": {
    code: "E-VIBECODR-0507",
    category: "api",
    httpStatus: 500,
    severity: "error",
    userMessage: "We could not load the feed response. Please retry.",
    logMessage: "Feed error JSON parse failed",
  },
  "E-VIBECODR-0508": {
    code: "E-VIBECODR-0508",
    category: "api",
    httpStatus: 502,
    severity: "error",
    userMessage: "Network error while loading the feed. Please retry.",
    logMessage: "Feed network error before response",
  },
  "E-VIBECODR-0509": {
    code: "E-VIBECODR-0509",
    category: "moderation",
    httpStatus: 500,
    severity: "error",
    userMessage: "Moderation status could not be loaded. Please retry.",
    logMessage: "Player moderation status JSON parse failed",
  },
  "E-VIBECODR-0510": {
    code: "E-VIBECODR-0510",
    category: "moderation",
    httpStatus: 502,
    severity: "error",
    userMessage: "Moderation status fetch failed. Please retry.",
    logMessage: "Player moderation status fetch failed",
  },
  "E-VIBECODR-0511": {
    code: "E-VIBECODR-0511",
    category: "api",
    httpStatus: 400,
    severity: "warning",
    userMessage: "Share failed or was cancelled. Please retry.",
    logMessage: "Player share via navigator.share failed",
  },
  "E-VIBECODR-0512": {
    code: "E-VIBECODR-0512",
    category: "api",
    httpStatus: 400,
    severity: "warning",
    userMessage: "Copy to clipboard failed. Please retry.",
    logMessage: "Player clipboard write failed",
  },
  "E-VIBECODR-0513": {
    code: "E-VIBECODR-0513",
    category: "moderation",
    httpStatus: 500,
    severity: "error",
    userMessage: "Flagged content handling failed. Please retry.",
    logMessage: "Flagged-post quarantine error JSON parse failed",
  },
  "E-VIBECODR-0514": {
    code: "E-VIBECODR-0514",
    category: "moderation",
    httpStatus: 500,
    severity: "error",
    userMessage: "Moderation resolve failed. Please retry.",
    logMessage: "Moderation resolve or origin parse failed",
  },
  "E-VIBECODR-0515": {
    code: "E-VIBECODR-0515",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Player log submission failed. Please retry.",
    logMessage: "Player appendLogs failed",
  },
  "E-VIBECODR-0516": {
    code: "E-VIBECODR-0516",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Player run completion failed. Please retry.",
    logMessage: "Player complete run failed",
  },
  "E-VIBECODR-0517": {
    code: "E-VIBECODR-0517",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Player moderation request failed. Please retry.",
    logMessage: "Player moderation request failed",
  },
  "E-VIBECODR-0520": {
    code: "E-VIBECODR-0520",
    category: "runtime",
    httpStatus: 400,
    severity: "warning",
    userMessage: "Runner origin is not configured; communication skipped.",
    logMessage: "Runner origin allowlist empty; skipping postMessage",
  },
  "E-VIBECODR-0521": {
    code: "E-VIBECODR-0521",
    category: "runtime",
    httpStatus: 400,
    severity: "warning",
    userMessage: "Runner origin is not configured; incoming message dropped.",
    logMessage: "Runner origin allowlist empty; dropping incoming message",
  },
  "E-VIBECODR-0522": {
    code: "E-VIBECODR-0522",
    category: "runtime",
    httpStatus: 400,
    severity: "warning",
    userMessage: "Runner parent origin missing; bridge traffic blocked.",
    logMessage: "Runner parent origin missing; blocking bridge traffic",
  },
  "E-VIBECODR-0523": {
    code: "E-VIBECODR-0523",
    category: "runtime",
    httpStatus: 400,
    severity: "warning",
    userMessage: "Runner origin allowlist is empty.",
    logMessage: "Runner origin allowlist empty",
  },
  "E-VIBECODR-0524": {
    code: "E-VIBECODR-0524",
    category: "runtime",
    httpStatus: 200,
    severity: "warning",
    userMessage: "Runtime events were capped for this session.",
    logMessage: "Runtime events capped for this session",
  },
  "E-VIBECODR-0525": {
    code: "E-VIBECODR-0525",
    category: "runtime",
    httpStatus: 200,
    severity: "warning",
    userMessage: "Runtime logs were capped for this session.",
    logMessage: "Runtime logs capped for this session",
  },
  "E-VIBECODR-0526": {
    code: "E-VIBECODR-0526",
    category: "runtime",
    httpStatus: 504,
    severity: "error",
    userMessage: "This app took too long to start. Please retry.",
    logMessage: "Runtime boot timeout exceeded; hard kill issued",
  },
  "E-VIBECODR-0527": {
    code: "E-VIBECODR-0527",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "This app was blocked due to a sandbox policy issue.",
    logMessage: "Sandbox misconfiguration detected; blocking runtime",
  },
  "E-VIBECODR-0530": {
    code: "E-VIBECODR-0530",
    category: "runtime",
    httpStatus: 200,
    severity: "warning",
    userMessage: "The app was stopped, but shutdown may not have completed cleanly.",
    logMessage: "Kill message not sent but UI stopped runtime",
  },

  // 07xx: studio import/export
  "E-VIBECODR-0701": {
    code: "E-VIBECODR-0701",
    category: "import",
    httpStatus: 400,
    severity: "error",
    userMessage: "Studio import failed. Please check the file and retry.",
    logMessage: "Studio import failed",
  },
  "E-VIBECODR-0702": {
    code: "E-VIBECODR-0702",
    category: "import",
    httpStatus: 500,
    severity: "error",
    userMessage: "Studio file save failed. Please retry.",
    logMessage: "Studio files save failed",
  },
  "E-VIBECODR-0703": {
    code: "E-VIBECODR-0703",
    category: "import",
    httpStatus: 500,
    severity: "error",
    userMessage: "Studio params save failed. Please retry.",
    logMessage: "Studio params save failed",
  },

  // 073x: capsule parameter recipes
  "E-VIBECODR-0730": {
    code: "E-VIBECODR-0730",
    category: "capsule",
    httpStatus: 400,
    severity: "error",
    userMessage: "Recipe is invalid. Please check the name and parameter values.",
    logMessage: "Capsule recipe payload validation failed",
  },
  "E-VIBECODR-0731": {
    code: "E-VIBECODR-0731",
    category: "capsule",
    httpStatus: 400,
    severity: "error",
    userMessage: "No valid parameters were provided for this recipe.",
    logMessage: "Capsule recipe contained no valid params",
  },
  "E-VIBECODR-0732": {
    code: "E-VIBECODR-0732",
    category: "capsule",
    httpStatus: 429,
    severity: "error",
    userMessage: "Recipe limit reached for this app. Please remove one before adding another.",
    logMessage: "Capsule recipe limit exceeded",
  },
  "E-VIBECODR-0733": {
    code: "E-VIBECODR-0733",
    category: "capsule",
    httpStatus: 500,
    severity: "error",
    userMessage: "Could not save recipe right now. Please retry.",
    logMessage: "Capsule recipe persistence failed",
  },
  "E-VIBECODR-0734": {
    code: "E-VIBECODR-0734",
    category: "capsule",
    httpStatus: 403,
    severity: "error",
    userMessage: "You cannot modify this recipe.",
    logMessage: "Capsule recipe modification forbidden",
  },
  "E-VIBECODR-0735": {
    code: "E-VIBECODR-0735",
    category: "capsule",
    httpStatus: 404,
    severity: "error",
    userMessage: "Recipe not found.",
    logMessage: "Capsule recipe not found",
  },

  // 08xx: analytics/import
  "E-VIBECODR-0801": {
    code: "E-VIBECODR-0801",
    category: "api",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Import analytics are temporarily unavailable.",
    logMessage: "Import analytics failed",
  },
  "E-VIBECODR-0802": {
    code: "E-VIBECODR-0802",
    category: "api",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Publish analytics are temporarily unavailable.",
    logMessage: "Publish analytics failed",
  },

  // 09xx: studio runtime
  "E-VIBECODR-0901": {
    code: "E-VIBECODR-0901",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Studio runtime failed to load. Please retry.",
    logMessage: "Studio runtime load failed",
  },
  "E-VIBECODR-0902": {
    code: "E-VIBECODR-0902",
    category: "api",
    httpStatus: 400,
    severity: "error",
    userMessage: "This remix would create a cycle. Please choose a different parent.",
    logMessage: "Remix cycle detected",
  },
  "E-VIBECODR-0903": {
    code: "E-VIBECODR-0903",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Unable to summarize files. Please retry.",
    logMessage: "Studio files summary failed",
  },
  "E-VIBECODR-0904": {
    code: "E-VIBECODR-0904",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Unable to load the selected file. Please retry.",
    logMessage: "Studio file load failed",
  },
  "E-VIBECODR-0905": {
    code: "E-VIBECODR-0905",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Unable to save the selected file. Please retry.",
    logMessage: "Studio file save failed",
  },
  "E-VIBECODR-0906": {
    code: "E-VIBECODR-0906",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Unable to save parameters. Please retry.",
    logMessage: "Studio params save failed",
  },
  "E-VIBECODR-0907": {
    code: "E-VIBECODR-0907",
    category: "api",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Unable to load plan information. Some features may be limited.",
    logMessage: "Plan quota fetch failed for plan gate",
  },
  "E-VIBECODR-0908": {
    code: "E-VIBECODR-0908",
    category: "runtime",
    httpStatus: 400,
    severity: "error",
    userMessage: "ZIP analysis failed. Please check the file and retry.",
    logMessage: "Advanced ZIP analyzer client-side analysis failed",
  },
  "E-VIBECODR-0909": {
    code: "E-VIBECODR-0909",
    category: "runtime",
    httpStatus: 400,
    severity: "warning",
    userMessage: "Invalid file type. Please select a ZIP file.",
    logMessage: "Advanced ZIP analyzer received non-ZIP file",
  },

  // 10xx: profiles and themes
  "E-VIBECODR-1002": {
    code: "E-VIBECODR-1002",
    category: "api",
    httpStatus: 400,
    severity: "error",
    userMessage: "Profile theme data is invalid.",
    logMessage: "Invalid profile theme row",
  },
  "E-VIBECODR-1003": {
    code: "E-VIBECODR-1003",
    category: "api",
    httpStatus: 400,
    severity: "error",
    userMessage: "Profile block configuration is invalid.",
    logMessage: "Invalid profile block config",
  },
  "E-VIBECODR-1004": {
    code: "E-VIBECODR-1004",
    category: "api",
    httpStatus: 400,
    severity: "error",
    userMessage: "Profile block data could not be parsed.",
    logMessage: "Profile block JSON parse failed",
  },
  "E-VIBECODR-1006": {
    code: "E-VIBECODR-1006",
    category: "api",
    httpStatus: 500,
    severity: "error",
    userMessage: "Profile theme lookup failed. Please retry.",
    logMessage: "Profile theme lookup failed",
  },
  "E-VIBECODR-1007": {
    code: "E-VIBECODR-1007",
    category: "api",
    httpStatus: 500,
    severity: "error",
    userMessage: "Profile badges lookup failed. Please retry.",
    logMessage: "Profile badges lookup failed",
  },

  // 11xx: compile/manifest/runtime setup
  "E-VIBECODR-1100": {
    code: "E-VIBECODR-1100",
    category: "manifest",
    httpStatus: 400,
    severity: "error",
    userMessage: "This app's configuration is invalid.",
    logMessage: "Manifest schema validation failed",
  },
  "E-VIBECODR-1101": {
    code: "E-VIBECODR-1101",
    category: "og-image",
    httpStatus: 502,
    severity: "warning",
    userMessage: "Post preview is temporarily unavailable.",
    logMessage: "OG image fetch for post failed",
  },
  "E-VIBECODR-1103": {
    code: "E-VIBECODR-1103",
    category: "manifest",
    httpStatus: 400,
    severity: "error",
    userMessage: "This app uses an unsupported import.",
    logMessage: "Manifest import allowlist violation",
  },
  "E-VIBECODR-1104": {
    code: "E-VIBECODR-1104",
    category: "runtime",
    httpStatus: 202,
    severity: "warning",
    userMessage: "Compile telemetry for this app may be temporarily degraded.",
    logMessage: "ArtifactCompiler state write failed while recording last compile request",
  },
  "E-VIBECODR-1105": {
    code: "E-VIBECODR-1105",
    category: "runtime",
    httpStatus: 202,
    severity: "warning",
    userMessage: "Compile telemetry for this app may be temporarily degraded.",
    logMessage: "ArtifactCompiler analytics datapoint write failed",
  },
  "E-VIBECODR-1106": {
    code: "E-VIBECODR-1106",
    category: "runtime",
    httpStatus: 502,
    severity: "error",
    userMessage: "Compile request failed while reading the error response.",
    logMessage: "Artifact compile error body read failed",
  },
  "E-VIBECODR-1108": {
    code: "E-VIBECODR-1108",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Artifact compile failed.",
    logMessage: "Artifact compile failed",
  },
  "E-VIBECODR-1109": {
    code: "E-VIBECODR-1109",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Artifact compile additional file read failed.",
    logMessage: "Artifact compile additional file read failed",
  },
  "E-VIBECODR-1114": {
    code: "E-VIBECODR-1114",
    category: "runtime",
    httpStatus: 202,
    severity: "warning",
    userMessage: "Bundle warning telemetry is temporarily degraded.",
    logMessage: "Artifact bundle warning telemetry write failed",
  },
  "E-VIBECODR-1110": {
    code: "E-VIBECODR-1110",
    category: "manifest",
    httpStatus: 400,
    severity: "error",
    userMessage: "This app is too large for the current plan.",
    logMessage: "Manifest bundle size exceeds allowed maximum",
  },

  // 12xx: runtime manifest retrieval
  "E-VIBECODR-1201": {
    code: "E-VIBECODR-1201",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "We couldn't load this app. Please try again.",
    logMessage: "Runtime manifest JSON parse failed",
  },
  "E-VIBECODR-1202": {
    code: "E-VIBECODR-1202",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "We couldn't load this app. Please try again.",
    logMessage: "getArtifactManifest handler failed",
  },
  "E-VIBECODR-1203": {
    code: "E-VIBECODR-1203",
    category: "runtime",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Runtime manifest cache is unavailable; retrying with a fallback.",
    logMessage: "Runtime manifest KV read failed",
  },
  "E-VIBECODR-1204": {
    code: "E-VIBECODR-1204",
    category: "runtime",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Runtime compile analytics failed. Telemetry may be delayed.",
    logMessage: "Runtime compile analytics failed",
  },

  // 13xx: artifact cache
  "E-VIBECODR-1301": {
    code: "E-VIBECODR-1301",
    category: "runtime",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Latest build cache read failed. Data may be stale.",
    logMessage: "Latest artifact cache read failed",
  },
  "E-VIBECODR-1302": {
    code: "E-VIBECODR-1302",
    category: "runtime",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Latest artifact cache write failed. Data may be stale.",
    logMessage: "Latest artifact cache write failed",
  },
  "E-VIBECODR-1303": {
    code: "E-VIBECODR-1303",
    category: "runtime",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Latest artifact cache invalidation failed.",
    logMessage: "Latest artifact cache invalidation failed",
  },

  // 20xx: misc API
  "E-VIBECODR-2001": {
    code: "E-VIBECODR-2001",
    category: "api",
    httpStatus: 500,
    severity: "error",
    userMessage: "Profile failed to load. Please retry.",
    logMessage: "Profile load failed",
  },
  "E-VIBECODR-2002": {
    code: "E-VIBECODR-2002",
    category: "api",
    httpStatus: 500,
    severity: "error",
    userMessage: "Profile response was invalid. Please refresh.",
    logMessage: "Invalid profile response shape",
  },

  // 21xx: runtime execution
  "E-VIBECODR-2101": {
    code: "E-VIBECODR-2101",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "The app crashed while running.",
    logMessage: "Artifact runtime crashed inside sandbox",
  },
  "E-VIBECODR-2102": {
    code: "E-VIBECODR-2102",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "The app failed while processing a runtime bridge message.",
    logMessage: "Runtime bridge handler threw while processing postMessage payload",
  },
  "E-VIBECODR-2120": {
    code: "E-VIBECODR-2120",
    category: "runtime",
    httpStatus: 403,
    severity: "error",
    userMessage: "Browser storage APIs are disabled inside this app.",
    logMessage: "Runtime guard blocked local/session storage access",
  },
  "E-VIBECODR-2121": {
    code: "E-VIBECODR-2121",
    category: "runtime",
    httpStatus: 403,
    severity: "error",
    userMessage: "Cookie access is disabled inside this app.",
    logMessage: "Runtime guard blocked document.cookie access",
  },
  "E-VIBECODR-2122": {
    code: "E-VIBECODR-2122",
    category: "runtime",
    httpStatus: 403,
    severity: "error",
    userMessage: "Navigation APIs are disabled inside this app.",
    logMessage: "Runtime guard blocked window.open/navigation attempt",
  },
  "E-VIBECODR-2130": {
    code: "E-VIBECODR-2130",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Runtime analytics collection is temporarily unavailable. Please retry.",
    logMessage: "Runtime analytics write failed",
  },
  "E-VIBECODR-2131": {
    code: "E-VIBECODR-2131",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Unable to load runtime analytics data right now.",
    logMessage: "Runtime analytics summary fetch failed",
  },
  "E-VIBECODR-2136": {
    code: "E-VIBECODR-2136",
    category: "runtime",
    httpStatus: 202,
    severity: "warning",
    userMessage: "Run log telemetry is temporarily unavailable; some logs may be missing.",
    logMessage: "Runtime appendRunLogs analytics write failed",
  },
  "E-VIBECODR-2107": {
    code: "E-VIBECODR-2107",
    category: "runtime",
    httpStatus: 400,
    severity: "error",
    userMessage: "Unsupported runtime type.",
    logMessage: "Unsupported runtime type requested",
  },
  "E-VIBECODR-2108": {
    code: "E-VIBECODR-2108",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Runtime loader failed to render.",
    logMessage: "Runtime loader failed to render",
  },
  "E-VIBECODR-2109": {
    code: "E-VIBECODR-2109",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Failed to load the runtime manifest.",
    logMessage: "Runtime manifest fetch failed",
  },
  "E-VIBECODR-2110": {
    code: "E-VIBECODR-2110",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Runtime manifest asset is missing.",
    logMessage: "Runtime manifest missing required asset",
  },
  "E-VIBECODR-2111": {
    code: "E-VIBECODR-2111",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "Failed to load the HTML bundle for this vibe.",
    logMessage: "HTML bundle fetch failed",
  },
  "E-VIBECODR-2112": {
    code: "E-VIBECODR-2112",
    category: "runtime",
    httpStatus: 500,
    severity: "error",
    userMessage: "The HTML runtime is not available. This may be a bug in Vibecodr.",
    logMessage: "HTML runtime not available after script load",
  },
  "E-VIBECODR-2132": {
    code: "E-VIBECODR-2132",
    category: "runtime",
    httpStatus: 429,
    severity: "warning",
    userMessage: "Runtime analytics rate limit exceeded.",
    logMessage: "Runtime analytics rate limit exceeded",
  },
  "E-VIBECODR-2133": {
    code: "E-VIBECODR-2133",
    category: "runtime",
    httpStatus: 413,
    severity: "error",
    userMessage: "Runtime event payload is too large.",
    logMessage: "Runtime event payload exceeded size limit",
  },
  "E-VIBECODR-2134": {
    code: "E-VIBECODR-2134",
    category: "runtime",
    httpStatus: 400,
    severity: "warning",
    userMessage: "Runtime event properties were truncated.",
    logMessage: "Runtime event properties not serializable or truncated",
  },
  "E-VIBECODR-2135": {
    code: "E-VIBECODR-2135",
    category: "runtime",
    httpStatus: 400,
    severity: "error",
    userMessage: "Runtime event timestamp is invalid.",
    logMessage: "Runtime event timestamp outside allowed skew or invalid",
  },

  // 22xx: schema checks
  "E-VIBECODR-2201": {
    code: "E-VIBECODR-2201",
    category: "api",
    httpStatus: 500,
    severity: "warning",
    userMessage: "Post visibility check failed. Defaults applied.",
    logMessage: "Post visibility column check failed",
  },
  "E-VIBECODR-2202": {
    code: "E-VIBECODR-2202",
    category: "api",
    httpStatus: 500,
    severity: "error",
    userMessage: "Profile data is unavailable. Please retry.",
    logMessage: "Invalid profile response",
  },
  "E-VIBECODR-2203": {
    code: "E-VIBECODR-2203",
    category: "api",
    httpStatus: 500,
    severity: "error",
    userMessage: "Your apps are temporarily unavailable. Please retry.",
    logMessage: "Invalid capsule response",
  },

  // 24xx: admin analytics
  "E-VIBECODR-2401": {
    code: "E-VIBECODR-2401",
    category: "api",
    httpStatus: 200,
    severity: "warning",
    userMessage: "Runtime analytics summary is missing health metrics.",
    logMessage: "Runtime analytics summary missing health metrics",
  },

  // 31xx: telemetry/demo UI
  "E-VIBECODR-3101": {
    code: "E-VIBECODR-3101",
    category: "internal",
    httpStatus: 200,
    severity: "warning",
    userMessage: "Telemetry send failed. Please retry.",
    logMessage: "Telemetry send failed",
  },

  // 32xx: admin inspector + diagnostics
  "E-VIBECODR-3201": {
    code: "E-VIBECODR-3201",
    category: "internal",
    httpStatus: 500,
    severity: "error",
    userMessage: "Inspector diagnostics are temporarily unavailable.",
    logMessage: "Inspector compile state fetch failed",
  },
  "E-VIBECODR-3202": {
    code: "E-VIBECODR-3202",
    category: "internal",
    httpStatus: 500,
    severity: "error",
    userMessage: "Inspector failed to load app or runtime manifests.",
    logMessage: "Inspector manifest parse or load failed",
  },
};

export type ErrorCode = keyof typeof definitions;

export const ERROR_AUTH_VERIFICATION_FAILED: ErrorCode = "E-VIBECODR-0001";
export const ERROR_AUTH_CLAIMS_INVALID: ErrorCode = "E-VIBECODR-0004";
export const ERROR_AUTH_AUDIENCE_MISMATCH: ErrorCode = "E-VIBECODR-0005";
export const ERROR_AUTH_SIGNATURE_INVALID: ErrorCode = "E-VIBECODR-0006";
export const ERROR_AUTH_JWKS_FETCH_FAILED: ErrorCode = "E-VIBECODR-0007";
export const ERROR_AUTH_JWKS_PARSE_FAILED: ErrorCode = "E-VIBECODR-0008";
export const ERROR_CAPSULE_ACCESS_BLOCKED: ErrorCode = "E-VIBECODR-0601";
export const ERROR_MANIFEST_INVALID: ErrorCode = "E-VIBECODR-1100";
export const ERROR_MANIFEST_TOO_LARGE: ErrorCode = "E-VIBECODR-1110";
export const ERROR_ARTIFACT_COMPILER_STATE_WRITE_FAILED: ErrorCode = "E-VIBECODR-1104";
export const ERROR_ARTIFACT_COMPILER_ANALYTICS_FAILED: ErrorCode = "E-VIBECODR-1105";
export const ERROR_BUNDLE_WARNING_TELEMETRY_FAILED: ErrorCode = "E-VIBECODR-1114";
export const ERROR_RUNTIME_MANIFEST_PARSE_FAILED: ErrorCode = "E-VIBECODR-1201";
export const ERROR_RUNTIME_MANIFEST_LOAD_FAILED: ErrorCode = "E-VIBECODR-1202";
export const ERROR_RUNTIME_MANIFEST_KV_UNAVAILABLE: ErrorCode = "E-VIBECODR-1203";
export const ERROR_RUNTIME_BRIDGE_HANDLER_FAILED: ErrorCode = "E-VIBECODR-2102";
export const ERROR_RUNTIME_STORAGE_BLOCKED: ErrorCode = "E-VIBECODR-2120";
export const ERROR_RUNTIME_COOKIE_BLOCKED: ErrorCode = "E-VIBECODR-2121";
export const ERROR_RUNTIME_NAVIGATION_BLOCKED: ErrorCode = "E-VIBECODR-2122";
export const ERROR_RUNTIME_ANALYTICS_FAILED: ErrorCode = "E-VIBECODR-2130";
export const ERROR_RUNTIME_ANALYTICS_SUMMARY_FAILED: ErrorCode = "E-VIBECODR-2131";
export const ERROR_INSPECTOR_COMPILE_STATE_FAILED: ErrorCode = "E-VIBECODR-3201";
export const ERROR_INSPECTOR_MANIFEST_LOAD_FAILED: ErrorCode = "E-VIBECODR-3202";
export const ERROR_PLAN_GATE_FETCH_FAILED: ErrorCode = "E-VIBECODR-0907";
export const ERROR_ADVANCED_ZIP_ANALYSIS_FAILED: ErrorCode = "E-VIBECODR-0908";
export const ERROR_ADVANCED_ZIP_INVALID_FILE: ErrorCode = "E-VIBECODR-0909";

export function getErrorDefinition(code: string): ErrorDefinition | undefined {
  return definitions[code];
}

export function isKnownErrorCode(code: string | undefined | null): code is ErrorCode {
  return !!code && code in definitions;
}
